name: "My Custom Docker Action"
description: "This is a sample custom Docker action."
inputs:
  message:
    description: "Message to print"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.message }}
