name: Docker Build and Test with Container

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Packages
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository }}:latest .

    - name: Push to GitHub Packages
      run: docker push ghcr.io/${{ github.repository }}:latest

    - name: Run container and test
      run: |
        docker run -d -p 3000:3000 --name test-app ghcr.io/${{ github.repository }}:latest
        sleep 5
        curl http://localhost:3000
