name: Simulated Test Run with Artifact

on: [push]

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Simulate test
      run: echo "All tests passed successfully!" > test-report.txt

    - name: Upload simulated report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: test-report.txt
