name: Run Simulated Tests on Self-Hosted Runners

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Simulate Test Output
      run: |
        echo "Running on ${{ matrix.os }}" > test-report.txt
        echo "Simulated test result: ✅ All good!" >> test-report.txt

    - name: Upload Test Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-report-${{ matrix.os }}
        path: test-report.txt
